/**
 * Sound presets — each one sets up waveform, envelopes, and parameters
 * to create a distinct robotic sound effect.
 *
 * Designed for a cute desktop companion robot — most presets favour
 * triangle / sine waveforms, gentle attack curves, and mid-high
 * frequencies so they sound warm and friendly rather than sharp.
 */
export const PRESETS = [
  /* ───────────────── Classic ───────────────── */
  {
    name: "Happy Chirp",
    category: "Classic",
    description: "Cheerful rising beep — great for confirmations & power-ups",
    icon: "😊",
    config: {
      durationMs: 350,
      waveform: "square",
      masterGain: 0.5,
      detune: 0,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.05, y: 1 },
        { x: 0.4, y: 0.8 },
        { x: 0.7, y: 0.9 },
        { x: 0.9, y: 0.3 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 600 },
        { x: 0.15, y: 1200 },
        { x: 0.5, y: 900 },
        { x: 0.75, y: 1800 },
        { x: 1, y: 1400 },
      ],
    },
  },
  {
    name: "Error Buzz",
    category: "Classic",
    description: "Low harsh buzz — perfect for errors & wrong answers",
    icon: "⚠️",
    config: {
      durationMs: 500,
      waveform: "sawtooth",
      masterGain: 0.45,
      detune: -20,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.03, y: 1 },
        { x: 0.15, y: 0.4 },
        { x: 0.3, y: 0.9 },
        { x: 0.5, y: 0.3 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 250 },
        { x: 0.2, y: 180 },
        { x: 0.5, y: 220 },
        { x: 1, y: 120 },
      ],
    },
  },
  {
    name: "Success Ding",
    category: "Classic",
    description: "Clean upward ping — ideal for success & achievements",
    icon: "✅",
    config: {
      durationMs: 300,
      waveform: "triangle",
      masterGain: 0.55,
      detune: 0,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.04, y: 1 },
        { x: 0.2, y: 0.7 },
        { x: 0.5, y: 0.4 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 800 },
        { x: 0.15, y: 1600 },
        { x: 0.4, y: 1400 },
        { x: 1, y: 1200 },
      ],
    },
  },
  {
    name: "Robot Boop",
    category: "Classic",
    description: "Short descending boop — classic robot acknowledgement",
    icon: "🤖",
    config: {
      durationMs: 200,
      waveform: "square",
      masterGain: 0.5,
      detune: 0,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 1 },
        { x: 0.5, y: 0.6 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1400 },
        { x: 0.3, y: 800 },
        { x: 1, y: 400 },
      ],
    },
  },
  {
    name: "Laser Zap",
    category: "Classic",
    description: "Fast downward sweep — for shooting & zapping effects",
    icon: "⚡",
    config: {
      durationMs: 180,
      waveform: "sawtooth",
      masterGain: 0.45,
      detune: 10,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.02, y: 1 },
        { x: 0.3, y: 0.7 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 3000 },
        { x: 0.1, y: 2000 },
        { x: 0.5, y: 600 },
        { x: 1, y: 150 },
      ],
    },
  },
  {
    name: "Coin Pickup",
    category: "Classic",
    description: "Two-note rising chime — for collectibles & rewards",
    icon: "🪙",
    config: {
      durationMs: 280,
      waveform: "square",
      masterGain: 0.45,
      detune: 0,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.04, y: 0.9 },
        { x: 0.3, y: 0.1 },
        { x: 0.4, y: 0 },
        { x: 0.44, y: 0.95 },
        { x: 0.75, y: 0.5 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 988 },
        { x: 0.35, y: 988 },
        { x: 0.42, y: 1319 },
        { x: 1, y: 1319 },
      ],
    },
  },

  /* ───────────────── Greetings ───────────────── */
  {
    name: "Hello!",
    category: "Greetings",
    description: "Warm two-tone greeting — a friendly hello when robot wakes up",
    icon: "👋",
    config: {
      durationMs: 400,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 25,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.85 },
        { x: 0.35, y: 0.2 },
        { x: 0.42, y: 0 },
        { x: 0.48, y: 0.9 },
        { x: 0.8, y: 0.4 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 700 },
        { x: 0.35, y: 850 },
        { x: 0.45, y: 1050 },
        { x: 1, y: 1100 },
      ],
    },
  },
  {
    name: "Goodbye Hum",
    category: "Greetings",
    description: "Gentle descending hum — a soft farewell before powering down",
    icon: "🌙",
    config: {
      durationMs: 500,
      waveform: "sine",
      masterGain: 0.4,
      detune: 20,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.1, y: 0.7 },
        { x: 0.4, y: 0.6 },
        { x: 0.7, y: 0.35 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 900 },
        { x: 0.3, y: 750 },
        { x: 0.7, y: 550 },
        { x: 1, y: 400 },
      ],
    },
  },
  {
    name: "Wake Up",
    category: "Greetings",
    description: "Bubbly rising tones — robot is booting up and happy to see you",
    icon: "☀️",
    config: {
      durationMs: 450,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 30,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.5 },
        { x: 0.15, y: 0.2 },
        { x: 0.22, y: 0.7 },
        { x: 0.35, y: 0.15 },
        { x: 0.42, y: 0.85 },
        { x: 0.75, y: 0.5 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 500 },
        { x: 0.15, y: 700 },
        { x: 0.3, y: 900 },
        { x: 0.45, y: 1150 },
        { x: 1, y: 1200 },
      ],
    },
  },

  /* ───────────────── Emotions ───────────────── */
  {
    name: "Giggle",
    category: "Emotions",
    description: "Quick wobbling chirps — the robot is laughing!",
    icon: "🤭",
    config: {
      durationMs: 420,
      waveform: "triangle",
      masterGain: 0.4,
      detune: 35,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.05, y: 0.7 },
        { x: 0.12, y: 0.1 },
        { x: 0.18, y: 0.75 },
        { x: 0.26, y: 0.1 },
        { x: 0.33, y: 0.8 },
        { x: 0.42, y: 0.1 },
        { x: 0.5, y: 0.65 },
        { x: 0.7, y: 0.3 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1000 },
        { x: 0.12, y: 1250 },
        { x: 0.25, y: 1050 },
        { x: 0.38, y: 1300 },
        { x: 0.55, y: 1100 },
        { x: 1, y: 1150 },
      ],
    },
  },
  {
    name: "Curious Hmm",
    category: "Emotions",
    description: "Rising inquisitive tone — robot is thinking about something",
    icon: "🧐",
    config: {
      durationMs: 380,
      waveform: "sine",
      masterGain: 0.42,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.1, y: 0.6 },
        { x: 0.5, y: 0.7 },
        { x: 0.8, y: 0.5 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 600 },
        { x: 0.4, y: 650 },
        { x: 0.7, y: 900 },
        { x: 1, y: 1100 },
      ],
    },
  },
  {
    name: "Sad Whimper",
    category: "Emotions",
    description: "Soft drooping tone — robot feels a little down",
    icon: "🥺",
    config: {
      durationMs: 500,
      waveform: "sine",
      masterGain: 0.35,
      detune: 40,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.1, y: 0.65 },
        { x: 0.35, y: 0.5 },
        { x: 0.65, y: 0.3 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 850 },
        { x: 0.2, y: 750 },
        { x: 0.5, y: 550 },
        { x: 0.8, y: 420 },
        { x: 1, y: 350 },
      ],
    },
  },
  {
    name: "Excited Squeal",
    category: "Emotions",
    description: "Quick rising squeak — robot is thrilled!",
    icon: "🎉",
    config: {
      durationMs: 300,
      waveform: "triangle",
      masterGain: 0.42,
      detune: 30,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.9 },
        { x: 0.25, y: 0.85 },
        { x: 0.5, y: 0.7 },
        { x: 0.8, y: 0.3 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 800 },
        { x: 0.1, y: 1200 },
        { x: 0.3, y: 1500 },
        { x: 0.6, y: 1700 },
        { x: 1, y: 1800 },
      ],
    },
  },
  {
    name: "Shy Peep",
    category: "Emotions",
    description: "Tiny quiet beep — robot is being bashful",
    icon: "😳",
    config: {
      durationMs: 180,
      waveform: "sine",
      masterGain: 0.3,
      detune: 10,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.15, y: 0.55 },
        { x: 0.45, y: 0.4 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1100 },
        { x: 0.3, y: 1050 },
        { x: 1, y: 950 },
      ],
    },
  },
  {
    name: "Love Purr",
    category: "Emotions",
    description: "Warm pulsing hum — robot is feeling cozy and affectionate",
    icon: "💕",
    config: {
      durationMs: 600,
      waveform: "sine",
      masterGain: 0.38,
      detune: 45,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.5 },
        { x: 0.2, y: 0.35 },
        { x: 0.3, y: 0.55 },
        { x: 0.42, y: 0.3 },
        { x: 0.55, y: 0.5 },
        { x: 0.7, y: 0.25 },
        { x: 0.85, y: 0.15 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 550 },
        { x: 0.3, y: 600 },
        { x: 0.6, y: 570 },
        { x: 1, y: 520 },
      ],
    },
  },
  {
    name: "Surprised Oop",
    category: "Emotions",
    description: "Quick up-then-down blip — robot didn't expect that!",
    icon: "😮",
    config: {
      durationMs: 250,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 20,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.9 },
        { x: 0.3, y: 0.7 },
        { x: 0.6, y: 0.4 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 700 },
        { x: 0.15, y: 1400 },
        { x: 0.4, y: 1350 },
        { x: 1, y: 800 },
      ],
    },
  },

  /* ───────────────── Notifications ───────────────── */
  {
    name: "Soft Ping",
    category: "Notifications",
    description: "Gentle notification chime — a polite nudge without startling",
    icon: "🔔",
    config: {
      durationMs: 250,
      waveform: "sine",
      masterGain: 0.4,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.75 },
        { x: 0.25, y: 0.5 },
        { x: 0.6, y: 0.2 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1200 },
        { x: 0.15, y: 1350 },
        { x: 1, y: 1250 },
      ],
    },
  },
  {
    name: "Reminder Nudge",
    category: "Notifications",
    description: "Double gentle tap — hey, don't forget about this!",
    icon: "📌",
    config: {
      durationMs: 350,
      waveform: "triangle",
      masterGain: 0.4,
      detune: 20,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.7 },
        { x: 0.2, y: 0.1 },
        { x: 0.3, y: 0 },
        { x: 0.36, y: 0.75 },
        { x: 0.6, y: 0.35 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 900 },
        { x: 0.2, y: 950 },
        { x: 0.33, y: 1000 },
        { x: 1, y: 1050 },
      ],
    },
  },
  {
    name: "Message Pop",
    category: "Notifications",
    description: "Bubbly pop sound — new message or chat notification",
    icon: "💬",
    config: {
      durationMs: 200,
      waveform: "sine",
      masterGain: 0.42,
      detune: 25,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.05, y: 0.85 },
        { x: 0.2, y: 0.6 },
        { x: 0.5, y: 0.25 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 650 },
        { x: 0.08, y: 1100 },
        { x: 0.3, y: 950 },
        { x: 1, y: 850 },
      ],
    },
  },
  {
    name: "Timer Done",
    category: "Notifications",
    description: "Three soft chimes — your timer or task is complete",
    icon: "⏰",
    config: {
      durationMs: 500,
      waveform: "triangle",
      masterGain: 0.42,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.05, y: 0.7 },
        { x: 0.18, y: 0.05 },
        { x: 0.28, y: 0 },
        { x: 0.33, y: 0.75 },
        { x: 0.48, y: 0.05 },
        { x: 0.55, y: 0 },
        { x: 0.6, y: 0.8 },
        { x: 0.85, y: 0.3 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1000 },
        { x: 0.25, y: 1000 },
        { x: 0.32, y: 1200 },
        { x: 0.55, y: 1200 },
        { x: 0.6, y: 1400 },
        { x: 1, y: 1400 },
      ],
    },
  },

  /* ───────────────── Actions ───────────────── */
  {
    name: "Yes / Agree",
    category: "Actions",
    description: "Quick affirmative double-beep — robot says yes!",
    icon: "👍",
    config: {
      durationMs: 280,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 20,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.8 },
        { x: 0.25, y: 0.1 },
        { x: 0.35, y: 0 },
        { x: 0.4, y: 0.85 },
        { x: 0.7, y: 0.4 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 800 },
        { x: 0.28, y: 850 },
        { x: 0.38, y: 1050 },
        { x: 1, y: 1100 },
      ],
    },
  },
  {
    name: "No / Deny",
    category: "Actions",
    description: "Soft low double-blip — a gentle refusal",
    icon: "🙅",
    config: {
      durationMs: 320,
      waveform: "sine",
      masterGain: 0.38,
      detune: 30,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.7 },
        { x: 0.22, y: 0.08 },
        { x: 0.32, y: 0 },
        { x: 0.38, y: 0.65 },
        { x: 0.65, y: 0.25 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 700 },
        { x: 0.25, y: 600 },
        { x: 0.35, y: 600 },
        { x: 0.6, y: 480 },
        { x: 1, y: 420 },
      ],
    },
  },
  {
    name: "Thinking…",
    category: "Actions",
    description: "Gentle wavering hum — robot is processing your request",
    icon: "💭",
    config: {
      durationMs: 600,
      waveform: "sine",
      masterGain: 0.32,
      detune: 40,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.1, y: 0.5 },
        { x: 0.3, y: 0.45 },
        { x: 0.5, y: 0.5 },
        { x: 0.7, y: 0.4 },
        { x: 0.9, y: 0.45 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 650 },
        { x: 0.2, y: 700 },
        { x: 0.4, y: 660 },
        { x: 0.6, y: 720 },
        { x: 0.8, y: 680 },
        { x: 1, y: 750 },
      ],
    },
  },
  {
    name: "Task Done",
    category: "Actions",
    description: "Satisfied completion chime — job well done!",
    icon: "🏁",
    config: {
      durationMs: 350,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 20,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.8 },
        { x: 0.3, y: 0.55 },
        { x: 0.5, y: 0.65 },
        { x: 0.8, y: 0.3 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 800 },
        { x: 0.15, y: 1000 },
        { x: 0.4, y: 1200 },
        { x: 0.6, y: 1250 },
        { x: 1, y: 1300 },
      ],
    },
  },

  /* ───────────────── Personality ───────────────── */
  {
    name: "Sleepy Yawn",
    category: "Personality",
    description: "Long slow descending sigh — robot is getting drowsy",
    icon: "😴",
    config: {
      durationMs: 700,
      waveform: "sine",
      masterGain: 0.3,
      detune: 35,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.12, y: 0.55 },
        { x: 0.35, y: 0.5 },
        { x: 0.6, y: 0.35 },
        { x: 0.85, y: 0.15 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 800 },
        { x: 0.15, y: 900 },
        { x: 0.4, y: 700 },
        { x: 0.7, y: 450 },
        { x: 1, y: 300 },
      ],
    },
  },
  {
    name: "Playful Boing",
    category: "Personality",
    description: "Bouncy spring sound — robot is in a silly mood",
    icon: "🤪",
    config: {
      durationMs: 320,
      waveform: "triangle",
      masterGain: 0.42,
      detune: 25,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.05, y: 0.85 },
        { x: 0.2, y: 0.5 },
        { x: 0.35, y: 0.7 },
        { x: 0.55, y: 0.35 },
        { x: 0.75, y: 0.2 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 500 },
        { x: 0.08, y: 1300 },
        { x: 0.25, y: 700 },
        { x: 0.4, y: 1100 },
        { x: 0.6, y: 800 },
        { x: 1, y: 900 },
      ],
    },
  },
  {
    name: "Proud Ta-da",
    category: "Personality",
    description: "Triumphant little fanfare — robot is showing off",
    icon: "🌟",
    config: {
      durationMs: 400,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 30,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.05, y: 0.6 },
        { x: 0.18, y: 0.15 },
        { x: 0.25, y: 0 },
        { x: 0.3, y: 0.7 },
        { x: 0.45, y: 0.15 },
        { x: 0.52, y: 0 },
        { x: 0.57, y: 0.85 },
        { x: 0.82, y: 0.4 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 800 },
        { x: 0.2, y: 850 },
        { x: 0.28, y: 1000 },
        { x: 0.48, y: 1050 },
        { x: 0.55, y: 1300 },
        { x: 1, y: 1350 },
      ],
    },
  },
  {
    name: "Confused Warble",
    category: "Personality",
    description: "Wobbly uncertain tone — robot doesn't understand",
    icon: "❓",
    config: {
      durationMs: 400,
      waveform: "sine",
      masterGain: 0.38,
      detune: 35,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.1, y: 0.6 },
        { x: 0.3, y: 0.55 },
        { x: 0.6, y: 0.5 },
        { x: 0.85, y: 0.55 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 750 },
        { x: 0.15, y: 850 },
        { x: 0.3, y: 700 },
        { x: 0.5, y: 900 },
        { x: 0.7, y: 720 },
        { x: 0.85, y: 950 },
        { x: 1, y: 1000 },
      ],
    },
  },
  {
    name: "Hungry Rumble",
    category: "Personality",
    description: "Low bubbly gurgle — robot needs to recharge",
    icon: "🔋",
    config: {
      durationMs: 500,
      waveform: "sine",
      masterGain: 0.35,
      detune: 50,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.45 },
        { x: 0.2, y: 0.3 },
        { x: 0.32, y: 0.5 },
        { x: 0.45, y: 0.25 },
        { x: 0.58, y: 0.45 },
        { x: 0.75, y: 0.2 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 350 },
        { x: 0.15, y: 420 },
        { x: 0.3, y: 330 },
        { x: 0.5, y: 400 },
        { x: 0.7, y: 310 },
        { x: 1, y: 280 },
      ],
    },
  },
  {
    name: "Sneezy Pfft",
    category: "Personality",
    description: "Quick burst then fade — achoo! Cute robot sneeze",
    icon: "🤧",
    config: {
      durationMs: 250,
      waveform: "triangle",
      masterGain: 0.4,
      detune: 20,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.03, y: 0.3 },
        { x: 0.1, y: 0.15 },
        { x: 0.14, y: 0.9 },
        { x: 0.25, y: 0.6 },
        { x: 0.5, y: 0.2 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 600 },
        { x: 0.1, y: 650 },
        { x: 0.15, y: 1400 },
        { x: 0.3, y: 900 },
        { x: 0.6, y: 600 },
        { x: 1, y: 450 },
      ],
    },
  },
];
