/**
 * Sound presets for a cute desktop companion robot.
 *
 * Design principles:
 *  - Triangle and sine waveforms dominate (softer harmonic content)
 *  - Gentle volume attacks (never 0 to 1 in under 5% of duration)
 *  - Musical frequency intervals (octaves, fifths, thirds)
 *  - Light detune (8-30 cents) for warmth, not wobble
 *  - No dead-silence gaps mid-sound: use low valleys (0.08-0.15)
 *    so notes blend smoothly
 */
export const PRESETS = [
  /* ---- Classic ---- */
  {
    name: "Happy Chirp",
    category: "Classic",
    description: "Cheerful rising beep — great for confirmations",
    icon: "\u{1F60A}",
    config: {
      durationMs: 300,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 12,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.85 },
        { x: 0.4, y: 0.75 },
        { x: 0.7, y: 0.5 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 800 },
        { x: 0.2, y: 1050 },
        { x: 0.5, y: 1200 },
        { x: 1, y: 1350 },
      ],
    },
  },
  {
    name: "Error Buzz",
    category: "Classic",
    description: "Two descending tones — something went wrong",
    icon: "\u26A0\uFE0F",
    config: {
      durationMs: 380,
      waveform: "square",
      masterGain: 0.35,
      detune: 0,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.8 },
        { x: 0.35, y: 0.15 },
        { x: 0.45, y: 0.1 },
        { x: 0.5, y: 0.75 },
        { x: 0.85, y: 0.3 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 520 },
        { x: 0.38, y: 480 },
        { x: 0.48, y: 390 },
        { x: 1, y: 350 },
      ],
    },
  },
  {
    name: "Success Ding",
    category: "Classic",
    description: "Clean upward chime — ideal for achievements",
    icon: "\u2705",
    config: {
      durationMs: 280,
      waveform: "triangle",
      masterGain: 0.5,
      detune: 8,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.07, y: 0.9 },
        { x: 0.25, y: 0.65 },
        { x: 0.55, y: 0.35 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 880 },
        { x: 0.15, y: 1100 },
        { x: 0.4, y: 1320 },
        { x: 1, y: 1320 },
      ],
    },
  },
  {
    name: "Robot Boop",
    category: "Classic",
    description: "Short descending boop — classic robot acknowledgement",
    icon: "\u{1F916}",
    config: {
      durationMs: 180,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 10,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.85 },
        { x: 0.4, y: 0.55 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1100 },
        { x: 0.2, y: 850 },
        { x: 0.6, y: 600 },
        { x: 1, y: 500 },
      ],
    },
  },
  {
    name: "Laser Zap",
    category: "Classic",
    description: "Fast downward sweep — for zapping effects",
    icon: "\u26A1",
    config: {
      durationMs: 160,
      waveform: "sawtooth",
      masterGain: 0.38,
      detune: 10,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.04, y: 0.9 },
        { x: 0.25, y: 0.65 },
        { x: 0.6, y: 0.3 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 2800 },
        { x: 0.15, y: 1800 },
        { x: 0.5, y: 600 },
        { x: 1, y: 200 },
      ],
    },
  },
  {
    name: "Coin Pickup",
    category: "Classic",
    description: "Two-note rising chime — for collectibles and rewards",
    icon: "\u{1FA99}",
    config: {
      durationMs: 260,
      waveform: "triangle",
      masterGain: 0.42,
      detune: 8,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.8 },
        { x: 0.32, y: 0.15 },
        { x: 0.42, y: 0.12 },
        { x: 0.48, y: 0.85 },
        { x: 0.75, y: 0.45 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 988 },
        { x: 0.36, y: 988 },
        { x: 0.44, y: 1320 },
        { x: 1, y: 1320 },
      ],
    },
  },

  /* ---- Greetings ---- */
  {
    name: "Hello!",
    category: "Greetings",
    description: "Warm two-tone greeting — a friendly hello",
    icon: "\u{1F44B}",
    config: {
      durationMs: 380,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.8 },
        { x: 0.3, y: 0.35 },
        { x: 0.4, y: 0.12 },
        { x: 0.48, y: 0.85 },
        { x: 0.75, y: 0.45 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 750 },
        { x: 0.32, y: 800 },
        { x: 0.44, y: 1000 },
        { x: 1, y: 1050 },
      ],
    },
  },
  {
    name: "Goodbye Hum",
    category: "Greetings",
    description: "Gentle descending hum — a soft farewell",
    icon: "\u{1F319}",
    config: {
      durationMs: 500,
      waveform: "sine",
      masterGain: 0.38,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.1, y: 0.65 },
        { x: 0.35, y: 0.55 },
        { x: 0.65, y: 0.35 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 880 },
        { x: 0.25, y: 780 },
        { x: 0.6, y: 600 },
        { x: 1, y: 440 },
      ],
    },
  },
  {
    name: "Wake Up",
    category: "Greetings",
    description: "Bubbly rising tones — robot is booting up",
    icon: "\u2600\uFE0F",
    config: {
      durationMs: 450,
      waveform: "triangle",
      masterGain: 0.42,
      detune: 18,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.07, y: 0.5 },
        { x: 0.18, y: 0.25 },
        { x: 0.25, y: 0.65 },
        { x: 0.38, y: 0.3 },
        { x: 0.46, y: 0.8 },
        { x: 0.7, y: 0.5 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 550 },
        { x: 0.2, y: 700 },
        { x: 0.4, y: 880 },
        { x: 0.6, y: 1050 },
        { x: 1, y: 1100 },
      ],
    },
  },

  /* ---- Emotions ---- */
  {
    name: "Giggle",
    category: "Emotions",
    description: "Quick wobbling chirps — the robot is laughing!",
    icon: "\u{1F92D}",
    config: {
      durationMs: 400,
      waveform: "triangle",
      masterGain: 0.4,
      detune: 20,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.65 },
        { x: 0.13, y: 0.2 },
        { x: 0.2, y: 0.7 },
        { x: 0.28, y: 0.2 },
        { x: 0.36, y: 0.75 },
        { x: 0.45, y: 0.25 },
        { x: 0.55, y: 0.6 },
        { x: 0.75, y: 0.25 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1050 },
        { x: 0.15, y: 1200 },
        { x: 0.3, y: 1100 },
        { x: 0.5, y: 1250 },
        { x: 0.7, y: 1150 },
        { x: 1, y: 1200 },
      ],
    },
  },
  {
    name: "Curious Hmm",
    category: "Emotions",
    description: "Rising inquisitive tone — robot is wondering",
    icon: "\u{1F9D0}",
    config: {
      durationMs: 350,
      waveform: "sine",
      masterGain: 0.42,
      detune: 12,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.1, y: 0.55 },
        { x: 0.4, y: 0.6 },
        { x: 0.7, y: 0.65 },
        { x: 0.9, y: 0.45 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 650 },
        { x: 0.2, y: 700 },
        { x: 0.5, y: 800 },
        { x: 0.8, y: 1000 },
        { x: 1, y: 1100 },
      ],
    },
  },
  {
    name: "Sad Whimper",
    category: "Emotions",
    description: "Soft drooping tone — robot feels a little down",
    icon: "\u{1F97A}",
    config: {
      durationMs: 450,
      waveform: "sine",
      masterGain: 0.35,
      detune: 25,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.1, y: 0.6 },
        { x: 0.3, y: 0.5 },
        { x: 0.6, y: 0.3 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 800 },
        { x: 0.15, y: 720 },
        { x: 0.4, y: 600 },
        { x: 0.7, y: 500 },
        { x: 1, y: 420 },
      ],
    },
  },
  {
    name: "Excited Squeal",
    category: "Emotions",
    description: "Quick bright burst — robot is thrilled!",
    icon: "\u{1F389}",
    config: {
      durationMs: 280,
      waveform: "triangle",
      masterGain: 0.42,
      detune: 18,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.55 },
        { x: 0.15, y: 0.2 },
        { x: 0.22, y: 0.85 },
        { x: 0.5, y: 0.6 },
        { x: 0.8, y: 0.25 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 900 },
        { x: 0.1, y: 1050 },
        { x: 0.25, y: 1320 },
        { x: 0.5, y: 1400 },
        { x: 1, y: 1450 },
      ],
    },
  },
  {
    name: "Shy Peep",
    category: "Emotions",
    description: "Tiny quiet beep — robot is being bashful",
    icon: "\u{1F633}",
    config: {
      durationMs: 160,
      waveform: "sine",
      masterGain: 0.32,
      detune: 8,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.12, y: 0.5 },
        { x: 0.35, y: 0.4 },
        { x: 0.7, y: 0.2 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1050 },
        { x: 0.2, y: 1020 },
        { x: 0.6, y: 950 },
        { x: 1, y: 880 },
      ],
    },
  },
  {
    name: "Love Purr",
    category: "Emotions",
    description: "Warm pulsing hum — robot feels cozy and affectionate",
    icon: "\u{1F495}",
    config: {
      durationMs: 550,
      waveform: "sine",
      masterGain: 0.38,
      detune: 22,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.5 },
        { x: 0.18, y: 0.35 },
        { x: 0.28, y: 0.55 },
        { x: 0.4, y: 0.35 },
        { x: 0.52, y: 0.5 },
        { x: 0.65, y: 0.3 },
        { x: 0.8, y: 0.2 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 700 },
        { x: 0.25, y: 740 },
        { x: 0.5, y: 720 },
        { x: 0.75, y: 700 },
        { x: 1, y: 680 },
      ],
    },
  },
  {
    name: "Surprised Oop",
    category: "Emotions",
    description: "Quick up-then-down blip — robot didn't expect that!",
    icon: "\u{1F62E}",
    config: {
      durationMs: 220,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.85 },
        { x: 0.35, y: 0.65 },
        { x: 0.65, y: 0.35 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 750 },
        { x: 0.12, y: 1100 },
        { x: 0.35, y: 1200 },
        { x: 0.6, y: 950 },
        { x: 1, y: 700 },
      ],
    },
  },

  /* ---- Notifications ---- */
  {
    name: "Soft Ping",
    category: "Notifications",
    description: "Gentle notification chime — a polite nudge",
    icon: "\u{1F514}",
    config: {
      durationMs: 220,
      waveform: "sine",
      masterGain: 0.4,
      detune: 10,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.7 },
        { x: 0.25, y: 0.5 },
        { x: 0.55, y: 0.25 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1100 },
        { x: 0.12, y: 1320 },
        { x: 0.4, y: 1300 },
        { x: 1, y: 1250 },
      ],
    },
  },
  {
    name: "Reminder Nudge",
    category: "Notifications",
    description: "Double gentle tap — hey, don't forget!",
    icon: "\u{1F4CC}",
    config: {
      durationMs: 320,
      waveform: "triangle",
      masterGain: 0.4,
      detune: 12,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.07, y: 0.7 },
        { x: 0.22, y: 0.15 },
        { x: 0.32, y: 0.1 },
        { x: 0.38, y: 0.75 },
        { x: 0.62, y: 0.4 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 880 },
        { x: 0.25, y: 920 },
        { x: 0.35, y: 1050 },
        { x: 0.6, y: 1050 },
        { x: 1, y: 1000 },
      ],
    },
  },
  {
    name: "Message Pop",
    category: "Notifications",
    description: "Bubbly pop sound — new message notification",
    icon: "\u{1F4AC}",
    config: {
      durationMs: 180,
      waveform: "sine",
      masterGain: 0.42,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.07, y: 0.8 },
        { x: 0.22, y: 0.55 },
        { x: 0.5, y: 0.25 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 700 },
        { x: 0.1, y: 1000 },
        { x: 0.3, y: 950 },
        { x: 1, y: 880 },
      ],
    },
  },
  {
    name: "Timer Done",
    category: "Notifications",
    description: "Three bright chimes — your timer is complete",
    icon: "\u23F0",
    config: {
      durationMs: 480,
      waveform: "triangle",
      masterGain: 0.42,
      detune: 10,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.7 },
        { x: 0.2, y: 0.12 },
        { x: 0.28, y: 0.1 },
        { x: 0.34, y: 0.75 },
        { x: 0.5, y: 0.12 },
        { x: 0.56, y: 0.1 },
        { x: 0.62, y: 0.8 },
        { x: 0.82, y: 0.35 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1050 },
        { x: 0.24, y: 1050 },
        { x: 0.3, y: 1320 },
        { x: 0.52, y: 1320 },
        { x: 0.58, y: 1580 },
        { x: 1, y: 1580 },
      ],
    },
  },

  /* ---- Actions ---- */
  {
    name: "Yes / Agree",
    category: "Actions",
    description: "Quick affirmative double-beep — robot says yes!",
    icon: "\u{1F44D}",
    config: {
      durationMs: 260,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 12,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.07, y: 0.75 },
        { x: 0.28, y: 0.15 },
        { x: 0.38, y: 0.1 },
        { x: 0.45, y: 0.8 },
        { x: 0.72, y: 0.4 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 880 },
        { x: 0.3, y: 880 },
        { x: 0.42, y: 1100 },
        { x: 1, y: 1100 },
      ],
    },
  },
  {
    name: "No / Deny",
    category: "Actions",
    description: "Soft descending double-blip — a gentle refusal",
    icon: "\u{1F645}",
    config: {
      durationMs: 300,
      waveform: "triangle",
      masterGain: 0.38,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.07, y: 0.7 },
        { x: 0.25, y: 0.12 },
        { x: 0.35, y: 0.1 },
        { x: 0.42, y: 0.65 },
        { x: 0.7, y: 0.25 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 780 },
        { x: 0.28, y: 750 },
        { x: 0.38, y: 620 },
        { x: 1, y: 580 },
      ],
    },
  },
  {
    name: "Thinking...",
    category: "Actions",
    description: "Gentle wavering hum — robot is processing",
    icon: "\u{1F4AD}",
    config: {
      durationMs: 550,
      waveform: "sine",
      masterGain: 0.35,
      detune: 18,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.5 },
        { x: 0.25, y: 0.45 },
        { x: 0.45, y: 0.5 },
        { x: 0.65, y: 0.45 },
        { x: 0.85, y: 0.4 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 700 },
        { x: 0.2, y: 730 },
        { x: 0.4, y: 710 },
        { x: 0.6, y: 740 },
        { x: 0.8, y: 720 },
        { x: 1, y: 750 },
      ],
    },
  },
  {
    name: "Task Done",
    category: "Actions",
    description: "Bright completion chime — job well done!",
    icon: "\u{1F3C1}",
    config: {
      durationMs: 300,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 10,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.6 },
        { x: 0.22, y: 0.12 },
        { x: 0.3, y: 0.1 },
        { x: 0.36, y: 0.85 },
        { x: 0.65, y: 0.45 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 1050 },
        { x: 0.25, y: 1050 },
        { x: 0.33, y: 1320 },
        { x: 1, y: 1320 },
      ],
    },
  },

  /* ---- Personality ---- */
  {
    name: "Sleepy Yawn",
    category: "Personality",
    description: "Long slow descending sigh — robot is getting drowsy",
    icon: "\u{1F634}",
    config: {
      durationMs: 650,
      waveform: "sine",
      masterGain: 0.32,
      detune: 18,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.1, y: 0.5 },
        { x: 0.3, y: 0.45 },
        { x: 0.55, y: 0.35 },
        { x: 0.8, y: 0.18 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 750 },
        { x: 0.12, y: 820 },
        { x: 0.3, y: 700 },
        { x: 0.6, y: 550 },
        { x: 1, y: 400 },
      ],
    },
  },
  {
    name: "Playful Boing",
    category: "Personality",
    description: "Bouncy spring sound — robot is in a silly mood",
    icon: "\u{1F92A}",
    config: {
      durationMs: 280,
      waveform: "triangle",
      masterGain: 0.42,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.85 },
        { x: 0.2, y: 0.55 },
        { x: 0.35, y: 0.65 },
        { x: 0.55, y: 0.35 },
        { x: 0.75, y: 0.2 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 600 },
        { x: 0.08, y: 1200 },
        { x: 0.22, y: 800 },
        { x: 0.38, y: 1050 },
        { x: 0.6, y: 880 },
        { x: 1, y: 900 },
      ],
    },
  },
  {
    name: "Proud Ta-da",
    category: "Personality",
    description: "Triumphant little fanfare — robot is showing off",
    icon: "\u{1F31F}",
    config: {
      durationMs: 400,
      waveform: "triangle",
      masterGain: 0.45,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.06, y: 0.6 },
        { x: 0.2, y: 0.18 },
        { x: 0.27, y: 0.12 },
        { x: 0.33, y: 0.65 },
        { x: 0.48, y: 0.18 },
        { x: 0.54, y: 0.12 },
        { x: 0.6, y: 0.85 },
        { x: 0.82, y: 0.4 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 880 },
        { x: 0.22, y: 880 },
        { x: 0.3, y: 1050 },
        { x: 0.5, y: 1050 },
        { x: 0.57, y: 1320 },
        { x: 1, y: 1320 },
      ],
    },
  },
  {
    name: "Confused Warble",
    category: "Personality",
    description: "Wobbly uncertain tone — robot doesn't understand",
    icon: "\u2753",
    config: {
      durationMs: 380,
      waveform: "sine",
      masterGain: 0.38,
      detune: 25,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.1, y: 0.55 },
        { x: 0.3, y: 0.5 },
        { x: 0.55, y: 0.5 },
        { x: 0.8, y: 0.5 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 780 },
        { x: 0.15, y: 850 },
        { x: 0.3, y: 750 },
        { x: 0.45, y: 870 },
        { x: 0.6, y: 760 },
        { x: 0.8, y: 880 },
        { x: 1, y: 920 },
      ],
    },
  },
  {
    name: "Hungry Rumble",
    category: "Personality",
    description: "Low bubbly gurgle — robot needs to recharge",
    icon: "\u{1F50B}",
    config: {
      durationMs: 480,
      waveform: "triangle",
      masterGain: 0.35,
      detune: 25,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.08, y: 0.45 },
        { x: 0.2, y: 0.25 },
        { x: 0.32, y: 0.5 },
        { x: 0.45, y: 0.2 },
        { x: 0.58, y: 0.45 },
        { x: 0.75, y: 0.2 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 450 },
        { x: 0.15, y: 520 },
        { x: 0.3, y: 440 },
        { x: 0.5, y: 500 },
        { x: 0.7, y: 430 },
        { x: 1, y: 400 },
      ],
    },
  },
  {
    name: "Sneezy Pfft",
    category: "Personality",
    description: "Quick burst then fade — achoo! Cute robot sneeze",
    icon: "\u{1F927}",
    config: {
      durationMs: 230,
      waveform: "triangle",
      masterGain: 0.4,
      detune: 15,
      volPoints: [
        { x: 0, y: 0 },
        { x: 0.05, y: 0.35 },
        { x: 0.12, y: 0.2 },
        { x: 0.16, y: 0.85 },
        { x: 0.3, y: 0.55 },
        { x: 0.55, y: 0.2 },
        { x: 1, y: 0 },
      ],
      freqPoints: [
        { x: 0, y: 700 },
        { x: 0.12, y: 750 },
        { x: 0.18, y: 1250 },
        { x: 0.35, y: 900 },
        { x: 0.65, y: 650 },
        { x: 1, y: 500 },
      ],
    },
  },
];
